---
- name: Converge - Uninstall (ssh)
  hosts: ssh
  gather_facts: yes
  become: yes
  vars:
    state: absent
  tasks:
    - name: "Include resource_self_description_service - state = absent"
      ansible.builtin.include_role:
        name: "resource_self_description_service"