---
# TODO: Set Download paths
- name: Set Download and binary name (amd64)
  ansible.builtin.set_fact:
    download_url: "https://github.com/{{ download_github_user }}/resource-self-description-service/releases/download/{{ resource_self_description_service_version }}/resource-self-description-service-{{ resource_self_description_service_version }}.jar"
  when:
    - ansible_distribution != 'Debian'
    - ansible_lsb.id != 'Raspbian'

- name: Set Download and binary name (armv7)
  ansible.builtin.set_fact:
    download_url: "https://github.com/{{ download_github_user }}/resource-self-description-service/releases/download/{{ resource_self_description_service_version }}/resource-self-description-{{ resource_self_description_service_version }}.jar"
  when:
    - ansible_distribution == 'Debian'
    - ansible_lsb.id == 'Raspbian'